# Generated by Django 5.2.6 on 2025-09-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Shop',
        ),
    ]
