# Generated by Django 5.2.6 on 2025-09-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('headband', 'Headband'), ('cone', 'Cone'), ('vest', 'Vest')], default='update', max_length=20),
        ),
    ]
